<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Daelon Morais" />
    <meta name="description" content="This is my website for Project 3 of SDS348">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project1 SDS348</title>
    <meta name="generator" content="Hugo 0.60.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project1.knit/">Project1 SDS348</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              <h2 id="introduction">Introduction</h2>
<p>The first dataset contains income and poverty data by county for all counties in Texas. It contains the variables: Counties, Per Capita Income, Median Household Income, and % of Population in Poverty. The second dataset contains data about the level of education and employment by county and contains the variables: Counties, % High School Graduate or Higher, % Bachelor s Degree or Higher, and Unemployment Rate (%). The third dataset contains data on opioid-related emergency department visits in 2017 by county. It contains the variables: Counties and Number of Opioid-Related Emergency Department Visits. Some data is suppressed from some of the counties due to privacy concerns and patient protection.
The first two datasets cam from the same source, the Texas Association of Counties. You can select a variety of variables and export the data from their website. The third dataset regard opioid-related visits to the ED came from the Department of State Health Services. They have an interactive data visualizer through their website, but I had to email them to get the raw CSV file.<br>
I chose these datasets becuase they are similar to the project I did in BIO328M but also very different. Back then, and currently, I am interest in emergency medicine as a potential career path. In biostatics, I looked into the association between education level and the number of trauma cases by county. Since that time, I have begun to be interested in the ongoing opioid epidemic and have decide to pursue research regarding the precribing of opioid in the emergency department. Although income, poverty, education, and employment are not variables I am investigating in my thesis, I thought it would be interesting to look into any possible associations between the variables.<br>
I assume to see poverty levels and unemployment rates to bepositively correlated to the number of opioid-related visits to the ED while expecting income and education to be negatively correlated to the number of opioid-related visits to the ED. This is due to socio-economic variables that affect drug abuse. The opioid data can be due to improper discharge instructions, lack of education about the dangers of the medication, addiction, and more.</p>
<h2 id="1-tidying-spreadgather">1. Tidying: Spread/Gather</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(dplyr)
</code></pre></div><pre><code>## 
## Attaching package: 'dplyr'
</code></pre><pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag
</code></pre><pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(ggplot2)
<span style="color:#a6e22e">library</span>(tidyverse)
</code></pre></div><pre><code>## ── Attaching packages ───────────────────────────────────────────────────────── tidyverse 1.3.0 ──
</code></pre><pre><code>## ✔ tibble  2.1.3     ✔ purrr   0.3.3
## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.4.0
</code></pre><pre><code>## ── Conflicts ──────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(readxl)
incomePoverty <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read_excel</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">~/Documents/UT/Classes/SDS 348/incomePoverty.xlsx&#34;</span>)
educationEmployment <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read_excel</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">~/Documents/UT/Classes/SDS 348/educationEmployment.xlsx&#34;</span>)
opioidEDvisits <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">read_excel</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">~/Documents/UT/Classes/SDS 348/opioidEDvisits.xlsx&#34;</span>)
<span style="color:#a6e22e">head</span>(incomePoverty)
</code></pre></div><pre><code>## # A tibble: 6 x 4
##   County    `Per Capita Incom… `Median Household Inco… `% of Population in Pove…
##   &lt;chr&gt;                  &lt;dbl&gt;                   &lt;dbl&gt;                     &lt;dbl&gt;
## 1 Anderson               33362                   42412                      18.8
## 2 Andrews                43105                   63451                      13  
## 3 Angelina               37555                   45318                      20  
## 4 Aransas                44820                   46970                      18.1
## 5 Archer                 47110                   58311                      10.1
## 6 Armstrong              45262                   55337                      10.6
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">head</span>(educationEmployment)
</code></pre></div><pre><code>## # A tibble: 6 x 4
##   County   `% High School Graduate … `% Bachelor s Degree o… `Unemployment Rate…
##   &lt;chr&gt;                        &lt;dbl&gt;                   &lt;dbl&gt;               &lt;dbl&gt;
## 1 Anderson                      80.2                    11.8                 3.6
## 2 Andrews                       73.8                    10.6                 3.1
## 3 Angelina                      79.9                    15.7                 5.1
## 4 Aransas                       83.2                    20.2                 6.8
## 5 Archer                        90.1                    21.8                 3.4
## 6 Armstro…                      89.8                    23.1                 2.5
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">head</span>(opioidEDvisits)
</code></pre></div><pre><code>## # A tibble: 6 x 2
##   County    `Number of Opioid-Related Emergency Department Visits`
##   &lt;chr&gt;                                                      &lt;dbl&gt;
## 1 Anderson                                                      21
## 2 Andrews                                                       10
## 3 Angelina                                                      25
## 4 Aransas                                                       11
## 5 Archer                                                        NA
## 6 Armstrong                                                     NA
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">incomePovertyUntidy<span style="color:#f92672">&lt;-</span>incomePoverty <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_longer</span>(<span style="color:#a6e22e">contains</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Income&#34;</span>))
incomePovertyUntidy<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">head</span>()
</code></pre></div><pre><code>## # A tibble: 6 x 4
##   County   `% of Population in Poverty` name                    value
##   &lt;chr&gt;                           &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;
## 1 Anderson                         18.8 Per Capita Income       33362
## 2 Anderson                         18.8 Median Household Income 42412
## 3 Andrews                          13   Per Capita Income       43105
## 4 Andrews                          13   Median Household Income 63451
## 5 Angelina                         20   Per Capita Income       37555
## 6 Angelina                         20   Median Household Income 45318
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">incomePovertyUntidy<span style="color:#f92672">&lt;-</span>incomePovertyUntidy <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_wider</span>(names_from<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">name&#34;</span>,values_from<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">value&#34;</span>)
incomePovertyUntidy<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">head</span>()
</code></pre></div><pre><code>## # A tibble: 6 x 4
##   County    `% of Population in Pove… `Per Capita Incom… `Median Household Inco…
##   &lt;chr&gt;                         &lt;dbl&gt;              &lt;dbl&gt;                   &lt;dbl&gt;
## 1 Anderson                       18.8              33362                   42412
## 2 Andrews                        13                43105                   63451
## 3 Angelina                       20                37555                   45318
## 4 Aransas                        18.1              44820                   46970
## 5 Archer                         10.1              47110                   58311
## 6 Armstrong                      10.6              45262                   55337
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">educationEmploymentUntidy<span style="color:#f92672">&lt;-</span>educationEmployment <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_longer</span>(<span style="color:#a6e22e">contains</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">%&#34;</span>))
educationEmploymentUntidy<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">head</span>()
</code></pre></div><pre><code>## # A tibble: 6 x 3
##   County   name                             value
##   &lt;chr&gt;    &lt;chr&gt;                            &lt;dbl&gt;
## 1 Anderson % High School Graduate or Higher  80.2
## 2 Anderson % Bachelor s Degree or Higher     11.8
## 3 Anderson Unemployment Rate (%)              3.6
## 4 Andrews  % High School Graduate or Higher  73.8
## 5 Andrews  % Bachelor s Degree or Higher     10.6
## 6 Andrews  Unemployment Rate (%)              3.1
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">educationEmploymentUntidy<span style="color:#f92672">&lt;-</span>educationEmploymentUntidy <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_wider</span>(names_from<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">name&#34;</span>,values_from<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">value&#34;</span>)
educationEmploymentUntidy<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">head</span>()     
</code></pre></div><pre><code>## # A tibble: 6 x 4
##   County   `% High School Graduate … `% Bachelor s Degree o… `Unemployment Rate…
##   &lt;chr&gt;                        &lt;dbl&gt;                   &lt;dbl&gt;               &lt;dbl&gt;
## 1 Anderson                      80.2                    11.8                 3.6
## 2 Andrews                       73.8                    10.6                 3.1
## 3 Angelina                      79.9                    15.7                 5.1
## 4 Aransas                       83.2                    20.2                 6.8
## 5 Archer                        90.1                    21.8                 3.4
## 6 Armstro…                      89.8                    23.1                 2.5
</code></pre><p>All of the datasets were already tidy. The opioidEDvisits datasets only had one column of a dependent variable. The incomePoverty and educationEmployment data had more variables to work with.
For the incomePoverty dataset, two of the columns had to do with income as a dollar amount while the last column concerned the poverty rate as a percentage. For that reason, I chose to make the dataset untidy by using pivot_longer to combine the income level columns which created a &ldquo;name&rdquo; column for per capita and median income level and a &ldquo;value&rdquo; column for the dollar amounts. I then used pivot_wider to separate the name column based on the name and the values followed, turning the dataset back to it's original form.</p>
<p>A similar process was carried out on the educationEmployment dataset; the three columns had to do with education level as a percentage of the population of the county. Therefore, I chose to make the dataset untidy by using pivot_longer to combine the columns that contained the &ldquo;%&rdquo; character which created a &ldquo;name&rdquo; column for each level of education and a &ldquo;value&rdquo; column for the percentage of the county's population that fit in each category. Then, I used pivot_wider to separate the name column based on the categories and the perccentages from the value column followed, returning the dataset to it's original form.</p>
<h2 id="2-joiningmerging">2. Joining/Merging</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">fulldata <span style="color:#f92672">&lt;-</span> opioidEDvisits <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">full_join</span>(incomePoverty, by<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">County&#34;</span>)<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">full_join</span>(educationEmployment, by<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">County&#34;</span>)
before <span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">nrow</span>(fulldata)
fulldata<span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">na.omit</span>(fulldata)
after<span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">nrow</span>(fulldata)
before<span style="color:#f92672">-</span>after
</code></pre></div><pre><code>## [1] 127
</code></pre><p>Since all of the datasets have the same counties as a common variable, I decided to use full_join. Using either left_join or right_join would have resulted in the same ending dataset and since there are matching columns in each, there are no rows dropped. 127 counties don't have data since it is suppressed due to privacy concerns and patient protection. I used na.omit() to remove these rows.</p>
<h2 id="3-wrangling">3. Wrangling</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#generate new var using mutate:</span>
fulldata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">mutate</span>(ED_visit_prop <span style="color:#f92672">=</span>`Number of Opioid-Related Emergency Department Visits`<span style="color:#f92672">/</span><span style="color:#a6e22e">sum</span>(`Number of Opioid-Related Emergency Department Visits`)) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">select</span>(County,ED_visit_prop) <span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">glimpse</span>()
</code></pre></div><pre><code>## Observations: 127
## Variables: 2
## $ County        &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Atascosa…
## $ ED_visit_prop &lt;dbl&gt; 0.002443565, 0.001163603, 0.002909006, 0.001279963, 0.0…
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#generate categories based on % of population with a Bachelor&#39;s Degree or higher and per capita income</span>
twoCatData<span style="color:#f92672">&lt;-</span> fulldata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">mutate</span>(percentDegreeRange<span style="color:#f92672">=</span><span style="color:#a6e22e">cut</span>(`% Bachelor s Degree or Higher`, breaks<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#f92672">-</span><span style="color:#66d9ef">Inf</span>,<span style="color:#ae81ff">16.2</span>,<span style="color:#ae81ff">21.7</span>,<span style="color:#66d9ef">Inf</span>), labels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">low&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">middle&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">high&#34;</span>)))<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">mutate</span>(perCapitaIncomeRange<span style="color:#f92672">=</span><span style="color:#a6e22e">cut</span>(`Per Capita Income`, breaks<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#f92672">-</span><span style="color:#66d9ef">Inf</span>,<span style="color:#ae81ff">37809</span>,<span style="color:#ae81ff">43412</span>,<span style="color:#66d9ef">Inf</span>), labels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">low&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">middle&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">high&#34;</span>)))
<span style="color:#75715e">#1)mean ED visits by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">select</span>(<span style="color:#a6e22e">c</span>(perCapitaIncomeRange,`Number of Opioid-Related Emergency Department Visits`)) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_ED<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Number of Opioid-Related Emergency Department Visits`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange mean_ED
##   &lt;fct&gt;                  &lt;dbl&gt;
## 1 low                     32.1
## 2 middle                  38.0
## 3 high                   134.
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#2)mean % Bachelor&#39;s Degree or higher by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_Degree<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`% Bachelor s Degree or Higher`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange mean_Degree
##   &lt;fct&gt;                      &lt;dbl&gt;
## 1 low                         17.1
## 2 middle                      18.7
## 3 high                        25.4
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#3)mean % High School Graduate or higher by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_High<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`% High School Graduate or Higher`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange mean_High
##   &lt;fct&gt;                    &lt;dbl&gt;
## 1 low                       78.7
## 2 middle                    82.7
## 3 high                      84.2
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#4)mean Unemployment by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_Unemploy<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Unemployment Rate (%)`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange mean_Unemploy
##   &lt;fct&gt;                        &lt;dbl&gt;
## 1 low                           4.58
## 2 middle                        4.36
## 3 high                          3.80
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#5)mean % of Population in Poverty by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_Pov<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`% of Population in Poverty`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange mean_Pov
##   &lt;fct&gt;                   &lt;dbl&gt;
## 1 low                      18.7
## 2 middle                   15.0
## 3 high                     11.7
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#6)mean per capita income by % of population with a Bachelor&#39;s Degree or higher</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(percentDegreeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_PerInc<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Per Capita Income`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   percentDegreeRange mean_PerInc
##   &lt;fct&gt;                    &lt;dbl&gt;
## 1 low                     39384.
## 2 middle                  40397.
## 3 high                    47779.
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#7)mean median income by % of population with a Bachelor&#39;s Degree or higher</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(percentDegreeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_MedInc<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Median Household Income`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   percentDegreeRange mean_MedInc
##   &lt;fct&gt;                    &lt;dbl&gt;
## 1 low                     48101.
## 2 middle                  50407.
## 3 high                    61735.
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#8)mean Unemployment by % of population with a Bachelor&#39;s Degree or higher</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(percentDegreeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_unemploy<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Unemployment Rate (%)`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   percentDegreeRange mean_unemploy
##   &lt;fct&gt;                      &lt;dbl&gt;
## 1 low                         4.66
## 2 middle                      4.4 
## 3 high                        3.69
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#9)mean % of Population in Poverty by % of population with a Bachelor&#39;s Degree or higher</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(percentDegreeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_Pov<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`% of Population in Poverty`,na.rm<span style="color:#f92672">=</span>T))
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   percentDegreeRange mean_Pov
##   &lt;fct&gt;                 &lt;dbl&gt;
## 1 low                    16.9
## 2 middle                 16.0
## 3 high                   12.5
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#10)mean ED visits by per capita income</span>
twoCatData <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange,percentDegreeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(mean_ED<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`Number of Opioid-Related Emergency Department Visits`,na.rm<span style="color:#f92672">=</span>T)) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">arrange</span>(mean_ED)
</code></pre></div><pre><code>## # A tibble: 9 x 3
## # Groups:   perCapitaIncomeRange [3]
##   perCapitaIncomeRange percentDegreeRange mean_ED
##   &lt;fct&gt;                &lt;fct&gt;                &lt;dbl&gt;
## 1 high                 middle                12  
## 2 low                  low                   15.7
## 3 low                  high                  15.8
## 4 middle               low                   18.7
## 5 middle               middle                43.4
## 6 middle               high                  53.5
## 7 low                  middle                59.8
## 8 high                 low                  140. 
## 9 high                 high                 181.
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#Of counties with high percentages of the population with a bachelor&#39;s degree or higher, what is the average poverty rate by per capita income</span>
twoCatData<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">filter</span>(percentDegreeRange<span style="color:#f92672">==</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">high&#34;</span>) <span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">group_by</span>(perCapitaIncomeRange) <span style="color:#f92672">%&gt;%</span>  <span style="color:#a6e22e">summarize</span>(avg_Pov<span style="color:#f92672">=</span><span style="color:#a6e22e">mean</span>(`% of Population in Poverty`)) 
</code></pre></div><pre><code>## # A tibble: 3 x 2
##   perCapitaIncomeRange avg_Pov
##   &lt;fct&gt;                  &lt;dbl&gt;
## 1 low                     20.5
## 2 middle                  13.1
## 3 high                    10.7
</code></pre><p>I used mutate to generate the variable ED_visit_prop which is a function of the Numer of Opioid Related ED Visits; it is the proportion of Opioid ED Visits by County to the whole state of Texas. I then generated high, medium, and low categories based on % of population with a Bachelor's Degree or higher and per capita income in order to carry out the summary statistics. I calculated the mean ED visits by per capita income: low income counties had an average of 32.1 ED visits, middle income counties had an average of 38.0 ED visits,and high income counties had an average of 134 ED visits. The average % Bachelor's Degree or higher for low income counties was 17.1%, middle income counties was 18.7%, and high income counties was 25.4%. I calculated the mean % of the population that was a High School Graduate or higher for low income counties was 78.7%, middle income counties was 82.7%, and high income counties was 84.2%. The mean Unemployment rate by per capita income was 4.58% for low income counties, 4.36% for middle imcome counties, and 3.80% for high income counties. The mean % of Population in Poverty by per capita income was 18.7% for low income counties, 15.0% for middle income counties, and 11.7% for high income counties. The high income counties, as expected, had a higher average percents of their populations graduate high shcool, earn a Bachelor's degree, and number of ED visits than low income counties. They also had lower average umemployment and poverty rates than their counterparts.</p>
<p>The mean per capita income by  % of population with a Bachelor's Degree or higher was $39384, $40397, and $47779 while the mean median income was $48101, $50407, and $61735. As expected, higher percentages of bachelor degree holders is associated with higher incomes. The mean Unemployment by % of population with a Bachelor's Degree or higher is 4.66%, 4.4%, and 3.69%. The mean % of Population in Poverty by % of population with a Bachelor's Degree or higher is 16.9%, 16.0%, and 12.5%. As expected, higher percentages of bachelor degree holders is associated with lower rates of poverty and umemployment. In counties with a high proportion of bachelor degree holders, the trend that counties with higher per capita incomes having lower poverty rates still holds true.</p>
<h2 id="4-visualizing">4. Visualizing</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ggplot</span>(fulldata, <span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>`% Bachelor s Degree or Higher`))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_point</span>(<span style="color:#a6e22e">aes</span>(y<span style="color:#f92672">=</span>`Per Capita Income`, size<span style="color:#f92672">=</span>(fulldata<span style="color:#f92672">$</span>`Number of Opioid-Related Emergency Department Visits`)), shape <span style="color:#f92672">=</span> <span style="color:#ae81ff">21</span>,colour<span style="color:#f92672">=</span><span style="color:#e6db74">&#39;</span><span style="color:#e6db74">black&#39;</span>,fill<span style="color:#f92672">=</span><span style="color:#e6db74">&#39;</span><span style="color:#e6db74">#1876f0&#39;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">scale_size_continuous</span>(name <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Opioid-Related ED Visits&#34;</span>)<span style="color:#f92672">+</span> <span style="color:#a6e22e">ggtitle</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Plot of Per Captia Income by % of a County&#39;s Population with a Bachelor&#39;s Degree or Higher&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">ylab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Per Capita Income ($)&#34;</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">County&#39;s Population with a Bachelor&#39;s Degree or Higher (%)&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">scale_y_continuous</span>(breaks<span style="color:#f92672">=</span><span style="color:#a6e22e">seq</span>(<span style="color:#ae81ff">0</span>,<span style="color:#ae81ff">80000</span>,<span style="color:#ae81ff">5000</span>))<span style="color:#f92672">+</span><span style="color:#a6e22e">theme</span>(axis.text.x <span style="color:#f92672">=</span> <span style="color:#a6e22e">element_text</span>(colour<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#f08f18&#34;</span>),axis.text.y <span style="color:#f92672">=</span> <span style="color:#a6e22e">element_text</span>(colour<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#65a11e&#34;</span>),plot.title <span style="color:#f92672">=</span> <span style="color:#a6e22e">element_text</span>(size<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span>))
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">fulldata1<span style="color:#f92672">&lt;-</span>fulldata
fulldata1<span style="color:#f92672">&lt;-</span>fulldata1<span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">pivot_longer</span>(<span style="color:#a6e22e">contains</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">%&#34;</span>))

<span style="color:#a6e22e">ggplot</span>(fulldata1, <span style="color:#a6e22e">aes</span>(x <span style="color:#f92672">=</span> name, y <span style="color:#f92672">=</span> value, fill<span style="color:#f92672">=</span>value))<span style="color:#f92672">+</span> <span style="color:#a6e22e">geom_bar</span>(stat<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">summary&#34;</span>,fun.y<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">mean&#34;</span>,fill<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#27b3b6&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#65a11e&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#f08f18&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">#b6277f&#34;</span>))<span style="color:#f92672">+</span><span style="color:#a6e22e">theme</span>(axis.text.x <span style="color:#f92672">=</span> <span style="color:#a6e22e">element_text</span>(angle<span style="color:#f92672">=</span><span style="color:#ae81ff">45</span>, hjust<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span>, size<span style="color:#f92672">=</span><span style="color:#ae81ff">10</span>))<span style="color:#f92672">+</span> <span style="color:#a6e22e">ggtitle</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Education and Economic Statistics of Texas Counties&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">ylab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Percentage of the Population (%)&#34;</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">Average of All County Statistics&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted -->
The &ldquo;Plot of Per Captia Income by % of a County's Population with a Bachelor's Degree or Higher&rdquo; scatterplot shows a somewhat positive association between the proportion of a county's population with a Bachelor's degree or higher and an increasing per capita income which is too be expected since higher levels of education typically accompany higher paying jobs. I set the size of the points to be proportional to the number of opioid related ED visits. There is less of a clear trend when it comes to this variable but it does appear that a higher number of ED visits is associated with higher per capita income. The reason for this is equally obfuscated but it is possible that having excess income or higher SES may lead to more risky health behaviours. This may also be due to the fact that those with a higher SES and income are more likely to have access to and utilize healthcare.
For the bar graph there are not any relationships or trends to look at in particular. The average proportion of the population that has graduated high school or higher is above 80% which seems quite high although I do not have any standards to compare it too. The unemployment rate also seems quite low, looking it up right now, the US current unemployment rate is 3.7% which is below the average 4.25% rate for Texas counties.</p>
<h2 id="5-dimensionality-reduction-20-pts">5. Dimensionality Reduction (20 pts)</h2>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#clean/scale data</span>
fulldata<span style="color:#f92672">&lt;-</span>fulldata<span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">mutate</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">OpioidVisits&#34;</span><span style="color:#f92672">=</span><span style="color:#a6e22e">cut</span>(`Number of Opioid-Related Emergency Department Visits`, breaks<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#f92672">-</span><span style="color:#66d9ef">Inf</span>, <span style="color:#ae81ff">13</span>,<span style="color:#ae81ff">36</span>,<span style="color:#66d9ef">Inf</span>), labels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">low&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">med&#34;</span>,<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">high&#34;</span>)))
fulldata_nums<span style="color:#f92672">&lt;-</span>fulldata <span style="color:#f92672">%&gt;%</span><span style="color:#a6e22e">select_if</span>(is.numeric)<span style="color:#f92672">%&gt;%</span>scale
<span style="color:#a6e22e">rownames</span>(fulldata_nums)<span style="color:#f92672">&lt;-</span>fulldata<span style="color:#f92672">$</span>County
fulldata_pca<span style="color:#f92672">&lt;-</span><span style="color:#a6e22e">princomp</span>(fulldata_nums)
<span style="color:#a6e22e">names</span>(fulldata_pca)
</code></pre></div><pre><code>## [1] &quot;sdev&quot;     &quot;loadings&quot; &quot;center&quot;   &quot;scale&quot;    &quot;n.obs&quot;    &quot;scores&quot;   &quot;call&quot;
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#summarize results</span>
<span style="color:#a6e22e">summary</span>(fulldata_pca, loadings<span style="color:#f92672">=</span>T)
</code></pre></div><pre><code>## Importance of components:
##                           Comp.1    Comp.2    Comp.3    Comp.4     Comp.5
## Standard deviation     1.8847111 1.0119144 0.9134095 0.8347249 0.68920244
## Proportion of Variance 0.5114753 0.1474425 0.1201341 0.1003279 0.06839569
## Cumulative Proportion  0.5114753 0.6589178 0.7790519 0.8793798 0.94777551
##                            Comp.6     Comp.7
## Standard deviation     0.53370212 0.27902498
## Proportion of Variance 0.04101408 0.01121041
## Cumulative Proportion  0.98878959 1.00000000
## 
## Loadings:
##                                                      Comp.1 Comp.2 Comp.3
## Number of Opioid-Related Emergency Department Visits  0.147  0.903       
## Per Capita Income                                     0.406        -0.239
## Median Household Income                               0.460         0.149
## % of Population in Poverty                           -0.464  0.235       
## % High School Graduate or Higher                      0.377 -0.277  0.443
## % Bachelor s Degree or Higher                         0.403  0.195  0.268
## Unemployment Rate (%)                                -0.287         0.801
##                                                      Comp.4 Comp.5 Comp.6
## Number of Opioid-Related Emergency Department Visits         0.386       
## Per Capita Income                                    -0.532 -0.275  0.638
## Median Household Income                              -0.373        -0.588
## % of Population in Poverty                            0.147 -0.490  0.132
## % High School Graduate or Higher                      0.461  0.270  0.439
## % Bachelor s Degree or Higher                         0.336 -0.680 -0.165
## Unemployment Rate (%)                                -0.476         0.100
##                                                      Comp.7
## Number of Opioid-Related Emergency Department Visits       
## Per Capita Income                                          
## Median Household Income                               0.526
## % of Population in Poverty                            0.669
## % High School Graduate or Higher                      0.327
## % Bachelor s Degree or Higher                        -0.353
## Unemployment Rate (%)                                -0.199
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#75715e">#deciding how many PC&#39;s to keep</span>
eigval<span style="color:#f92672">&lt;-</span>fulldata_pca<span style="color:#f92672">$</span>sdev^2<span style="color:#75715e">#square to convert SDs to eigenvalues</span>
varprop<span style="color:#f92672">=</span><span style="color:#a6e22e">round</span>(eigval<span style="color:#f92672">/</span><span style="color:#a6e22e">sum</span>(eigval),<span style="color:#ae81ff">2</span>) <span style="color:#75715e">#proportion of var explained by each PC</span>
</code></pre></div><p>I scaled and selected the numeric variables from my data to use with princomp. I then used the summary function to look at the standard deviation, proportion of variance, and cummulative proportion of each PC.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_bar</span>(<span style="color:#a6e22e">aes</span>(y<span style="color:#f92672">=</span>varprop,x<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">7</span>),stat<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">identity&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_path</span>(<span style="color:#a6e22e">aes</span>(y<span style="color:#f92672">=</span>varprop,x<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">7</span>))<span style="color:#f92672">+</span>  <span style="color:#a6e22e">geom_text</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">7</span>,y<span style="color:#f92672">=</span>varprop,label<span style="color:#f92672">=</span><span style="color:#a6e22e">round</span>(varprop,<span style="color:#ae81ff">2</span>)),vjust<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span>,col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">white&#34;</span>,size<span style="color:#f92672">=</span><span style="color:#ae81ff">5</span>)<span style="color:#f92672">+</span>  <span style="color:#a6e22e">scale_y_continuous</span>(breaks<span style="color:#f92672">=</span><span style="color:#a6e22e">seq</span>(<span style="color:#ae81ff">0</span>,<span style="color:#ae81ff">.6</span>,<span style="color:#ae81ff">.2</span>),labels <span style="color:#f92672">=</span> scales<span style="color:#f92672">::</span>percent)<span style="color:#f92672">+</span>  <span style="color:#a6e22e">scale_x_continuous</span>(breaks<span style="color:#f92672">=</span><span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">10</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>The first 4 PC make up .78 (close to .8) of the total variance proportion and it's hard to tell where the &ldquo;elbow&rdquo; is so I chose them to continue with.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(ggrepel)
fulldata_df<span style="color:#f92672">&lt;-</span> fulldata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">mutate</span>(PC1<span style="color:#f92672">=</span>fulldata_pca<span style="color:#f92672">$</span>scores[,<span style="color:#ae81ff">1</span>], PC2<span style="color:#f92672">=</span>fulldata_pca<span style="color:#f92672">$</span>scores[,<span style="color:#ae81ff">2</span>])
<span style="color:#a6e22e">ggplot</span>(fulldata_df, <span style="color:#a6e22e">aes</span>(PC1,PC2,color<span style="color:#f92672">=</span>OpioidVisits))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_point</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_text_repel</span>(<span style="color:#a6e22e">aes</span>(label<span style="color:#f92672">=</span>County),color<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">black&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>PC1 does not seem to adequately separate the dataset based on whether the county in question has a high, medium, or low amount of opioid related ED visits. PC2 also does not do a very good job of sepaparting the number opioid ED visits but a high number opioid ED visits does appear to be higher than the low and medium visits.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">fulldata_df<span style="color:#f92672">&lt;-</span> fulldata <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">mutate</span>(PC3<span style="color:#f92672">=</span>fulldata_pca<span style="color:#f92672">$</span>scores[,<span style="color:#ae81ff">3</span>], PC4<span style="color:#f92672">=</span>fulldata_pca<span style="color:#f92672">$</span>scores[,<span style="color:#ae81ff">4</span>])
<span style="color:#a6e22e">ggplot</span>(fulldata_df, <span style="color:#a6e22e">aes</span>(PC3,PC4,color<span style="color:#f92672">=</span>OpioidVisits))<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_point</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_text_repel</span>(<span style="color:#a6e22e">aes</span>(label<span style="color:#f92672">=</span>County),color<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">black&#34;</span>)
</code></pre></div><p><!-- raw HTML omitted --></p>
<p>Just like PC 1&amp;2, PC4 does not seem to  separate the dataset based on whether the county in question has a high, medium, or low amount of opioid related ED visits nor does PC4. However,</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">fulldata_pca<span style="color:#f92672">$</span>loadings[2<span style="color:#f92672">:</span><span style="color:#ae81ff">7</span>,<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">2</span>]<span style="color:#f92672">%&gt;%</span>as.data.frame<span style="color:#f92672">%&gt;%</span>rownames_to_column <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_hline</span>(<span style="color:#a6e22e">aes</span>(yintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_vline</span>(<span style="color:#a6e22e">aes</span>(xintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">ylab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">PC2&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">PC1&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_segment</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,y<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,xend<span style="color:#f92672">=</span>Comp.1,yend<span style="color:#f92672">=</span>Comp.2), arrow<span style="color:#f92672">=</span><span style="color:#a6e22e">arrow</span>(),col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">red&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_label</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>Comp.1<span style="color:#f92672">*</span><span style="color:#ae81ff">1.1</span>,y<span style="color:#f92672">=</span>Comp.2<span style="color:#f92672">*</span><span style="color:#ae81ff">1.1</span>,label<span style="color:#f92672">=</span>rowname))
</code></pre></div><p><!-- raw HTML omitted --></p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">fulldata_pca<span style="color:#f92672">$</span>loadings[2<span style="color:#f92672">:</span><span style="color:#ae81ff">7</span>,<span style="color:#ae81ff">3</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>]<span style="color:#f92672">%&gt;%</span>as.data.frame<span style="color:#f92672">%&gt;%</span>rownames_to_column <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">ggplot</span>()<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_hline</span>(<span style="color:#a6e22e">aes</span>(yintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_vline</span>(<span style="color:#a6e22e">aes</span>(xintercept<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>),lty<span style="color:#f92672">=</span><span style="color:#ae81ff">2</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">ylab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">PC4&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">xlab</span>(<span style="color:#e6db74">&#34;</span><span style="color:#e6db74">PC3&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_segment</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,y<span style="color:#f92672">=</span><span style="color:#ae81ff">0</span>,xend<span style="color:#f92672">=</span>Comp.3,yend<span style="color:#f92672">=</span>Comp.4), arrow<span style="color:#f92672">=</span><span style="color:#a6e22e">arrow</span>(),col<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;</span><span style="color:#e6db74">red&#34;</span>)<span style="color:#f92672">+</span><span style="color:#a6e22e">geom_label</span>(<span style="color:#a6e22e">aes</span>(x<span style="color:#f92672">=</span>Comp.3<span style="color:#f92672">*</span><span style="color:#ae81ff">1.1</span>,y<span style="color:#f92672">=</span>Comp.4<span style="color:#f92672">*</span><span style="color:#ae81ff">1.1</span>,label<span style="color:#f92672">=</span>rowname))
</code></pre></div><p><!-- raw HTML omitted -->
For the plot with PC1 and PC2: The angles between vectors interpreted as correlations so % having a bachelor's Degree or higher and Per capital income are highly correlated wiith each other and negatively correlated with PC1 and  % in poverty and unemployment rateare correlated with each other and psitively with PC1. % in poverty and unemployment rate are not strongly correlated with % having a bachelor's Degree or higher, Median household income, % high school graduate or higher, nor Per capital income.
For the plot with PC3 and PC4: % in poverty, % high school graduate or higher, and % having a bachelor's Degree or higher are highly correlated and ot highly correlated with Unemployment rate, median household income, and per capita income.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
